import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/Components/Container";
import { Header } from "@/Components/Header";
import { Footer } from "@/Components/Footer";

export const metadata: Metadata = {
  title: {
    default: "Portfolio | Milena Albuquerque",
    template: '%s | Portifolio',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <Container>
          <Header />

          {children}

          <Footer />
        </Container>
        
      </body>
    </html>
  );
}
